---

- block:
  - name: Send failure notification via telegram
    telegram:
      token: "{{ telegram_token }}"
      api_args:
        chat_id: "{{ telegram_chat_id }}"
        parse_mode: "markdown"
        text: "⚠️  Ansible provision failed on *{{ ansible_hostname }}*\n\n
          *Task*:  {{ ansible_failed_task.name }}\n
          *Action*: {{ ansible_failed_task.action }}\n
          *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}```"
    changed_when: False

  rescue:
  - name: Send failure notification via telegram
    telegram:
      token: "{{ telegram_token }}"
      api_args:
        chat_id: "{{ telegram_chat_id }}"
        parse_mode: "markdown"
        text: "⚠️  Ansible provision failed on *{{ ansible_hostname }}*\n\n
          The specific error couldn't be shown, check the log."
    changed_when: False

- name: Ansible job failed, clear cache later on to trigger another provision run
  become: yes
  at:
    command: "if ! pgrep -f ansible-pull >/dev/null; then rm -rf /home/{{ custom_user }}/.ansible; fi"
    count: 60
    units: minutes
